from pathlib import Path
import pandas as pd


"""
This file takes the counties detail file and aggregates to CBSAs.
"""


counties = pd.read_csv(
    Path.cwd() / "prepped" / "1980" / "counties_with_details_1980.csv",
    dtype={"state_code": "str", "county_code": "str"},
)

cbsa_crosswalk = pd.read_csv(
    Path.cwd() / "raw" / "cbsa_crosswalk.csv",
    dtype={"state_code": "str", "county_code": "str"},
)[["state_code", "county_code", "cbsa_code", "cbsa_title"]]

counties.merge(cbsa_crosswalk, on=["state_code", "county_code"]).groupby(
    "cbsa_code"
).agg(
    {
        "cbsa_title": "first",
        "state_code": "first",
        "county_code": "first",
        "persons": "sum",
        "households": "sum",
        "age_lt_1": "sum",
        "age_1_to_2": "sum",
        "age_3_to_4": "sum",
        "age_5": "sum",
        "age_6": "sum",
        "age_7_to_9": "sum",
        "age_10_to_13": "sum",
        "age_14": "sum",
        "age_15": "sum",
        "age_16": "sum",
        "age_17": "sum",
        "age_18": "sum",
        "age_19": "sum",
        "age_20": "sum",
        "age_21": "sum",
        "age_22_to_24": "sum",
        "age_25_to_29": "sum",
        "age_30_to_34": "sum",
        "age_35_to_44": "sum",
        "age_45_to_54": "sum",
        "age_55_to_59": "sum",
        "age_60_to_61": "sum",
        "age_62_to_64": "sum",
        "age_65_to_74": "sum",
        "age_75_to_84": "sum",
        "age_ge_85": "sum",
        "inc_lt_2500": "sum",
        "inc_2500_4999": "sum",
        "inc_5000_7499": "sum",
        "inc_7500_9999": "sum",
        "inc_10000_12499": "sum",
        "inc_12500_14999": "sum",
        "inc_15000_17499": "sum",
        "inc_17500_19999": "sum",
        "inc_20000_22499": "sum",
        "inc_22500_24999": "sum",
        "inc_25000_27499": "sum",
        "inc_27500_29999": "sum",
        "inc_30000_34999": "sum",
        "inc_35000_39999": "sum",
        "inc_40000_49999": "sum",
        "inc_50000_74999": "sum",
        "inc_ge_75000": "sum",
        "worked_35_plus": "sum",
        "worked_1_to_34_hours": "sum",
        "car_truck_or_van__drive_alone": "sum",
        "car_truck_or_van__carpool": "sum",
        "public_transportation": "sum",
        "walked_only": "sum",
        "other_means": "sum",
        "worked_at_home": "sum",
        "commute_lt_5": "sum",
        "commute_5_to_9": "sum",
        "commute_10_to_14": "sum",
        "commute_15_to_20": "sum",
        "commute_20_to_29": "sum",
        "commute_30_to_44": "sum",
        "commute_45_to_59": "sum",
        "commute_gt_60": "sum",
        "jan_ave_temp": "mean",
        "feb_ave_temp": "mean",
        "mar_ave_temp": "mean",
        "apr_ave_temp": "mean",
        "may_ave_temp": "mean",
        "june_ave_temp": "mean",
        "july_ave_temp": "mean",
        "aug_ave_temp": "mean",
        "sept_ave_temp": "mean",
        "oct_ave_temp": "mean",
        "nov_ave_temp": "mean",
        "dec_ave_temp": "mean",
        "jan_precip": "mean",
        "feb_precip": "mean",
        "mar_precip": "mean",
        "apr_precip": "mean",
        "may_precip": "mean",
        "june_precip": "mean",
        "july_precip": "mean",
        "aug_precip": "mean",
        "sept_precip": "mean",
        "oct_precip": "mean",
        "nov_precip": "mean",
        "dec_precip": "mean",
        "ag_forestry_fish_mining": "sum",
        "construction": "sum",
        "manufacturing_nondurable": "sum",
        "manufacturing_durable": "sum",
        "transportation": "sum",
        "comms_and_util": "sum",
        "wholesale_trade": "sum",
        "retail_trade": "sum",
        "finance_insurance_realestate": "sum",
        "business_repair": "sum",
        "personal_entertainment_and_rec": "sum",
        "health_services": "sum",
        "educational_services": "sum",
        "other_pro_services": "sum",
        "public_admin": "sum",  # 15
    }
).to_csv(
    Path.cwd() / "prepped" / "1980" / "cbsa_details_1980.csv"
)
