import numpy as np
from weights import (
    POP_WEIGHT,
    AGE_WEIGHT,
    INCOME_WEIGHT,
    INDUSTRY_WEIGHT,
    COMMUTE_WEIGHT,
    WEATHER_WEIGHT
)

# Set weights to indicator topics to adjust comparisons

available_variables = [
    "state_code",
    "county_code",
    "persons",
    "households",
    "age_lt_1",
    "age_1_to_2",
    "age_3_to_4",
    "age_5",
    "age_6",
    "age_7_to_9",
    "age_10_to_13",
    "age_14",
    "age_15",
    "age_16",
    "age_17",
    "age_18",
    "age_19",
    "age_20",
    "age_21",
    "age_22_to_24",
    "age_25_to_29",
    "age_30_to_34",
    "age_35_to_44",
    "age_45_to_54",
    "age_55_to_59",
    "age_60_to_61",
    "age_62_to_64",
    "age_65_to_74",
    "age_75_to_84",
    "age_ge_85",
    "inc_lt_2500",
    "inc_2500_4999",
    "inc_5000_7499",
    "inc_7500_9999",
    "inc_10000_12499",
    "inc_12500_14999",
    "inc_15000_17499",
    "inc_17500_19999",
    "inc_20000_22499",
    "inc_22500_24999",
    "inc_25000_27499",
    "inc_27500_29999",
    "inc_30000_34999",
    "inc_35000_39999",
    "inc_40000_49999",
    "inc_50000_74999",
    "inc_ge_75000",
    "worked_35_plus",
    "worked_1_to_34_hours",
    "car_truck_or_van__drive_alone",
    "car_truck_or_van__carpool",
    "public_transportation",
    "walked_only",
    "other_means",
    "worked_at_home",
    "commute_lt_5",
    "commute_5_to_9",
    "commute_10_to_14",
    "commute_15_to_20",
    "commute_20_to_29",
    "commute_30_to_44",
    "commute_45_to_59",
    "commute_gt_60",
    "jan_ave_temp",
    "feb_ave_temp",
    "mar_ave_temp",
    "apr_ave_temp",
    "may_ave_temp",
    "june_ave_temp",
    "july_ave_temp",
    "aug_ave_temp",
    "sept_ave_temp",
    "oct_ave_temp",
    "nov_ave_temp",
    "dec_ave_temp",
    "jan_precip",
    "feb_precip",
    "mar_precip",
    "apr_precip",
    "may_precip",
    "june_precip",
    "july_precip",
    "aug_precip",
    "sept_precip",
    "oct_precip",
    "nov_precip",
    "dec_precip"
    "ag_forestry_fish_mining",
    "construction",
    "manufacturing_nondurable",
    "manufacturing_durable",
    "transportation",
    "comms_and_util",
    "wholesale_trade",
    "retail_trade",
    "finance_insurance_realestate",
    "business_repair",
    "personal_entertainment_and_rec",
    "health_services",
    "educational_services",
    "other_pro_services",
    "public_admin",  # 15
]


industry_variables = [  # for industry-reduction analysis
    "ag_forestry_fish_mining",
    "construction",
    "manufacturing_nondurable",
    "manufacturing_durable",
    "transportation",
    "comms_and_util",
    "wholesale_trade",
    "retail_trade",
    "finance_insurance_realestate",
    "business_repair",
    "personal_entertainment_and_rec",
    "health_services",
    "educational_services",
    "other_pro_services",
    "public_admin",  # 15
]


engineered_variables = [
    "persons",
    # NEED TO INCLUDE INDUSTRY SUMMARY VARIABLES
    # ONCE INDUSTRY ANALYSIS IS COMPLETE
    "pct_commute_lt_15",
    "pct_commute_15_to_44",
    "pct_commute_ge_45",
    "min_ave_monthy_temp",
    "max_ave_monthy_temp",
    "min_ave_monthy_precip",
    "max_ave_monthy_precip",
    "pct_age_lt_10",
    "pct_age_10_to_19",
    "pct_age_20_to_29",
    "pct_age_35_to_54",
    "pct_age_55_to_64",
    "pct_age_ge_65",
    "low_inc",
    "mid_inc",
    "hi_inc",
    "labor",
    "life_qual",
    "biz_financial",
]

scale = np.array([
    POP_WEIGHT,
    COMMUTE_WEIGHT,
    COMMUTE_WEIGHT,
    COMMUTE_WEIGHT,
    WEATHER_WEIGHT,
    WEATHER_WEIGHT,
    WEATHER_WEIGHT,
    WEATHER_WEIGHT,
    AGE_WEIGHT,
    AGE_WEIGHT,
    AGE_WEIGHT,
    AGE_WEIGHT,
    AGE_WEIGHT,
    AGE_WEIGHT,
    INCOME_WEIGHT,
    INCOME_WEIGHT,
    INCOME_WEIGHT,
    INDUSTRY_WEIGHT,
    INDUSTRY_WEIGHT,
    INDUSTRY_WEIGHT,
])
